### ISSUE TITLE
ubuntu 20.04 LVM not created as per user-data

### ISSUE THREAD

**Issue by amitchettri** [marcinbojko/hv-packer#9]
Hi @marcinbojko,

Following your step i did a small modification to add more FS in the LVM but the image create takes/create its LVM. I hope that can help me out to create the FS as below rather then 1 getting created of its currently
```yaml
storage:
  config:
    - {ptable: gpt, path: /dev/sda, wipe: superblock, preserve: false, name: '', grub_device: true, type: disk, id: disk-sda}
    - {device: disk-sda, size: 1M, flag: bios_grub, number: 1, preserve: false, grub_device: false, type: partition, id: partition-0}
    - {device: disk-sda, size: 1G, wipe: superblock, flag: '', number: 2, preserve: false, grub_device: false, type: partition, id: partition-1}
    - {device: disk-sda, size: 69G, wipe: superblock, flag: '', number: 3, preserve: false, grub_device: false, type: partition, id: partition-2}
    - name: ubuntu-vg
      devices: [partition-2]
      preserve: false
      type: lvm_volgroup
      id: lvm_volgroup-0
    - {fstype: xfs, volume: partition-1, preserve: false, type: format, id: format-2}
    - {name: swap, volgroup: lvm_volgroup-0, size: 2G, preserve: false, type: lvm_partition, id: lvm_partition-1}
    - {fstype: swap, volume: lvm_partition-1, preserve: false, type: format, id: format-3}
    - {device: format-3, path: '', type: mount, id: mount-3}
    - {name: var, volgroup: lvm_volgroup-0, size: 5G, preserve: false, type: lvm_partition, id: lvm_partition-2}
    - {fstype: xfs, volume: lvm_partition-2, preserve: false, type: format, id: format-4}
    - {name: tmp, volgroup: lvm_volgroup-0, size: 5G, preserve: false, type: lvm_partition, id: lvm_partition-3}
    - {fstype: xfs, volume: lvm_partition-3, preserve: false, type: format, id: format-5}
    - {name: var-log, volgroup: lvm_volgroup-0, size: 5G, preserve: false, type: lvm_partition, id: lvm_partition-4}
    - {fstype: xfs, volume: lvm_partition-4, preserve: false, type: format, id: format-6}
    - {name: var-log-audit, volgroup: lvm_volgroup-0, size: 5G, preserve: false, type: lvm_partition, id: lvm_partition-5}
    - {fstype: xfs, volume: lvm_partition-5, preserve: false, type: format, id: format-7}
    - {name: var-tmp, volgroup: lvm_volgroup-0, size: 5G, preserve: false, type: lvm_partition, id: lvm_partition-6}
    - {fstype: xfs, volume: lvm_partition-6, preserve: false, type: format, id: format-8}
    - {name: home, volgroup: lvm_volgroup-0, size: 10G, preserve: false, type: lvm_partition, id: lvm_partition-7}
    - {fstype: xfs, volume: lvm_partition-7, preserve: false, type: format, id: format-9}
    - {name: root, volgroup: lvm_volgroup-0, size: 34G, preserve: false, type: lvm_partition, id: lvm_partition-8}
    - {device: format-10, path: /, type: mount, id: mount-10}
    - {device: format-2, path: /boot, type: mount, id: mount-2}
    - {device: format-4, path: /var, type: mount, id: mount-4}
    - {device: format-5, path: /tmp, type: mount, id: mount-5}
    - {device: format-6, path: /var/log, type: mount, id: mount-6}
    - {device: format-7, path: /var-log-audit, type: mount, id: mount-7}
    - {device: format-8, path: /var/tmp, type: mount, id: mount-8}
    - {device: format-9, path: /home, type: mount, id: mount-9}
```

After image is created i see the lvdisplay and df -h details as below
![image](https://user-images.githubusercontent.com/46727623/123632855-0d6ccd80-d836-11eb-96e2-0fad59bf15e8.png)
![image](https://user-images.githubusercontent.com/46727623/123632874-12318180-d836-11eb-866b-b5c7794260d3.png)
